services:
  # Spring Boot 애플리케이션
  backend:
    build: ./backend
    container_name: travel-app-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/travel_app
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-travel_user}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-travel_password}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mysql
    restart: unless-stopped

  # Redis 서비스
  redis:
    image: redis:7-alpine
    container_name: travel-app-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: travel-app-mysql
    environment:
      # 개발용 기본값 - 운영 환경에서는 반드시 환경변수로 덮어쓰기
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-3251}
      MYSQL_DATABASE: travel_app
      MYSQL_USER: ${DB_USERNAME:-travel_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-travel_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  redis_data:
  mysql_data: