spring:
  jpa:
    hibernate:
      ddl-auto: validate  # 프로덕션에서는 스키마 변경 금지
    show-sql: false       # SQL 로그 비활성화 (성능 최적화)
    properties:
      hibernate:
        format_sql: false

  # 정적 리소스 매핑 활성화 (프론트엔드 빌드 파일 서빙용)
  web:
    resources:
      add-mappings: true

# 로깅 설정 (프로덕션)
logging:
  level:
    com.travelapp.backend: INFO     # DEBUG → INFO로 변경
    org.springframework.web: WARN   # DEBUG → WARN으로 변경
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log      # 로그 파일 저장
    max-size: 10MB
    max-history: 30                 # 30일치 로그 보관
